In [1]:
import numpy as np

from nltk.stem import PorterStemmer, WordNetLemmatizer
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import string
from nltk.corpus import stopwords
import math
from collections import Counter
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ha_ha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ha_ha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

## Strip function
- \n is absorbed when printing only that text
- \n is not absorbed when printing all the texts in a list

In [2]:
with open("01.Vector_Space_Retrieval\\bread.txt") as f:
    content = f.readlines()
    
print(content, '\n')
print([x.strip() for x in content], '\n')
print(content[0].strip('How'))

['How to Bake Breads Without Baking Recipes\n', 'Smith Pies: Best Pies in London\n', 'Numerical Recipes: The Art of Scientific Computing\n', 'Breads, Pastries, Pies, and Cakes: Quantity Baking Recipes\n', 'Pastry: A Book of Best French Pastry Recipes'] 

['How to Bake Breads Without Baking Recipes', 'Smith Pies: Best Pies in London', 'Numerical Recipes: The Art of Scientific Computing', 'Breads, Pastries, Pies, and Cakes: Quantity Baking Recipes', 'Pastry: A Book of Best French Pastry Recipes'] 

 to Bake Breads Without Baking Recipes



## Stopwords removal
- remove special characters !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
- "".join tells us not to add any spacings between the characters

In [3]:
text = "".join([ch for ch in content[1] if ch not in string.punctuation])
print(text)

Smith Pies Best Pies in London



## Tokenize vs Split

In [62]:
print(content[1])
print(nltk.word_tokenize(content[1]))
print(content[1].split())

Smith Pies: Best Pies in London

['Smith', 'Pies', ':', 'Best', 'Pies', 'in', 'London']
['Smith', 'Pies:', 'Best', 'Pies', 'in', 'London']


## Counter

In [68]:
# Convert the sentences into a list of list-of-words
sentences = [sentence.split() for sentence in content]
# Flatten the list
words = [word for sentence in sentences for word in sentence]

# Counter
counts = Counter(words)

# Print the count for the word recipe
print(counts['Recipes'])

# Print the 2 most common words
print(counts.most_common(2))

# Print the count of the most common word
print(counts.most_common(1)[0][1])

# !!!!!! Cannot flatten lists 
# sentences = [sentence.split() for sentence in content]
# print(sentences.flatten())

3
[('Recipes', 3), ('of', 2)]
3


AttributeError: 'list' object has no attribute 'flatten'

## Sorting

In [6]:
d_dict = {}
d_dict['a'] = 1

d_set = {7,2,3}
print(d_set)

{2, 3, 7}


# Regular expressions

#### Extracting text

In [5]:
import re

a = "apple is a fruit. he is a king"
b = "red algae, such as gelidium"

# set pattern
regexp_a = re.compile("[a-z]+ is a [a-z]+")
regexp_b = re.compile("[a-z]+, such as [a-z]+")

#Find all matches with the given regular expression
matches_a = re.findall(regexp_a, a)
matches_b = re.findall(regexp_b, b)
print(matches_a)
print(matches_b)

['apple is a fruit', 'he is a king']
['algae, such as gelidium']


#### Splitting and joining text

In [33]:
a = "apple orange man"
a = a.split(' ')
print(a)
print(" ".join(a))

['apple', 'orange', 'man']
apple orange man


#### Substituting text

In [73]:
a = "apple orange orange man"
print(re.sub(pattern="orange",repl="cake",string=a))

apple cake cake man


# Dictionaries

#### sorting the elements of a dictionary element

In [7]:
d = {}
d['apple'] = {}
d['apple']['apple'] = 0.41334243636
d['apple']['brand'] = 0.0915626602388
d['apple']['company'] = 0.0747098410221
d['apple']['crop'] = 0.147812587177

sorted(d['apple'].items(), key= lambda x: x[1])

[('company', 0.0747098410221),
 ('brand', 0.0915626602388),
 ('crop', 0.147812587177),
 ('apple', 0.41334243636)]

#### sorting the elements of a dictionary

In [10]:
students = ['dave', 'john', 'jane']
newgrades = {'john': 'F', 'jane':'A', 'dave': 'C'}
print(sorted(newgrades.items(), key= lambda x: x[0]))

[('dave', 'C'), ('jane', 'A'), ('john', 'F')]


#### looping through a dictionary

In [14]:
newgrades = {'john': 'F', 'jane':'A', 'dave': 'C'}
for key,value in newgrades.items():
    print(key,value)

jane A
john F
dave C


# Array Indexing

#### split array and print elements that are equal to value

In [15]:
temp = np.array([1,2,1,2,1,2,1,2,1])
l = temp[:4]
r = temp[4:]
print(l[l == 1])

[1 1]


#### Array looping

In [28]:
temp = np.array([1,2,3,4,5,6,7])
print(temp[::-1])
print(temp[-1:0:-1])
print(temp[::-2])

[7 6 5 4 3 2 1]
[7 6 5 4 3 2]
[7 5 3 1]


#### Sorting

In [44]:
temp = np.array([3,1,4,5,2])
tamp = np.array([[3,3,3,3,3],[1,1,1,1,1],[4,4,4,4,4],[5,5,5,5,5],[2,2,2,2,2]])
ind = np.argsort(temp)
print(temp[ind])
print(tamp[ind,:])

[1 2 3 4 5]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


#### Where

In [68]:
temp = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
ind = np.where((temp == 3) | (temp == 13))

print(ind[0]) # 1st element
print(ind[1]) # 2nd element

[0 2]
[2 2]


#### Setter

In [69]:
temp = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
temp[temp == 13] = 0
print(temp)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0 14 15]]


# Lists

#### Initialize list

In [18]:
# initialize list
l = [0]*3
print(l)

[0, 0, 0]


#### Sorting list

In [19]:
scores = [[0.5,"a"], [0.7,"b"], [0.9,"c"]]
scores.sort(key=lambda x: -x[0])
print(scores)

[[0.9, 'c'], [0.7, 'b'], [0.5, 'a']]


# Pandas

#### Indexing

In [12]:
import pandas as pd

# get all elements whose tweet_id equals 82846118
#data[data['tweet_id'] == 82846118]

# get all columns below
#data= data[['tweet_id','emotion', 'tweet_body']]

# list all the unique tweet_ids
#data.tweet_id.unique()

# indexing by location and label
df = pd.DataFrame({'month': [1, 4, 4, 10], 'year': [2012, 2014, 2013, 2014], 'string':['test1', 'test2', 'test3', 'test4']})
df = df.set_index('string')
#print(df)

# append column to pandas
#df['e'] = [9, 9, 9, 9]
#print(df)

# append column from pandas to pandas
#print(df['e'])
#df['g'] = df['e']
#print(df)

# get the most frequently occuring value in month
#print(df['month'].value_counts().idxmax())

print(df.iloc[0]['month'])

1


# Others

In [7]:
def pearson(x,y):
    
    mu_x = np.mean(x)
    mu_y = np.mean(y)
    
    del_x = x - mu_x
    del_y = y - mu_y
    
    numerator = del_x.del_y
    denominator = np.linalg.norm(del_x,2)*np.linalg.norm(del_y,2)
    
    return numerator/denominator

2.449489742783178
2.449489742783178


In [24]:
from sklearn.feature_extraction.text import CountVectorizer

sentence = ['haha haha lol funny']
cv = CountVectorizer()
word_counts = cv.fit_transform(sentence)

print("feature names\n", cv.get_feature_names())

print("word counts\n", word_counts.A)

print("pandas dataframe\n", pd.DataFrame(word_counts.A, columns=cv.get_feature_names()))

feature names
 ['funny', 'haha', 'lol']
word counts
 [[1 2 1]]
pandas dataframe
    funny  haha  lol
0      1     2    1


In [28]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])

print(precision_recall_fscore_support(y_true, y_pred))
print(precision_recall_fscore_support(y_true, y_pred)[0])

(array([0.66666667, 0.        , 0.        ]), array([1., 0., 0.]), array([0.8, 0. , 0. ]), array([2, 2, 2], dtype=int64))
[0.66666667 0.         0.        ]


#### Generate random numbers

In [74]:
print(np.random.randint(low=1, high=100, size=4))

[68 96 99 50]


In [18]:
a = np.array([1,2,3,0,0])
b = np.array([4,5,6,0,0])

def cosine_similarity(a,b):
    numerator = a.dot(b)
    denominator = np.linalg.norm(a,2) * np.linalg.norm(b,2)
    
    return numerator/denominator
print(cosine_similarity(a,b))

c = np.array([1,2,3])
d = np.array([3,6,9])
print(cosine_similarity(c,d))

0.9746318461970762
1.0


In [8]:
def H(a,b):
    return -(a/(a+b))*np.log2(a/(a+b)) -(b/(a+b))*np.log2(b/(a+b))

H(3,6)
#print(0.75*H(0.65/(0.65+0.1), 0.1/(0.65+0.1)) + 0.25*H(0.1/(0.15+0.1), 0.15/(0.15+0.1)))

0.9182958340544896